# Generated by Django 4.2.11 on 2024-05-14 11:30

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0013_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('img', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Фото')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=100, verbose_name='Iмя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Призвіще')),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True, verbose_name='По-батькові')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефону')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Користувача',
                'verbose_name_plural': 'Користувачі',
                'db_table': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Місто')),
                ('village', models.CharField(blank=True, max_length=50, null=True, verbose_name='Населений пункт')),
                ('street', models.CharField(blank=True, max_length=50, null=True, verbose_name='Вулиця')),
                ('house', models.PositiveIntegerField(blank=True, verbose_name='Будинок')),
                ('apartment', models.PositiveIntegerField(blank=True, verbose_name='Квартира')),
            ],
            options={
                'verbose_name': 'Адресу',
                'verbose_name_plural': 'Адреси',
                'db_table': 'Address',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('tab_nomer', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Табельний номер')),
                ('stazh', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cтаж')),
                ('specialization', models.CharField(max_length=100, verbose_name='Спеціалізація')),
                ('Umovy_pryyomu', models.CharField(blank=True, max_length=250, null=True, verbose_name='Умови прийому')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ID користувача')),
            ],
            options={
                'verbose_name': 'Лікаря',
                'verbose_name_plural': 'Лікарі',
                'db_table': 'Doctor',
            },
        ),
        migrations.CreateModel(
            name='FamilyDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.doctor', verbose_name='Лікар')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='Група')),
            ],
            options={
                'verbose_name': 'Cімейного лікаря',
                'verbose_name_plural': 'Сімейні лікарі',
                'db_table': 'FamilyDoctor',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(blank=True, choices=[('Ч', 'Чоловік'), ('Ж', 'Жінка')], max_length=1, null=True, verbose_name='Cтать')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата народження')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_app.address', verbose_name='Адреса')),
                ('id_doctor', models.ManyToManyField(through='auth_app.FamilyDoctor', to='auth_app.doctor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ID користувача')),
            ],
            options={
                'verbose_name': 'Пацієнта',
                'verbose_name_plural': 'Пацієнти',
                'db_table': 'Patient',
            },
        ),
        migrations.AddField(
            model_name='familydoctor',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.patient', verbose_name='Пацієнт'),
        ),
    ]
