# Generated by Django 4.2.11 on 2024-05-17 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='familydoctor',
            unique_together={('patient', 'doctor')},
        ),
    ]
