# Generated by Django 4.2.11 on 2024-04-23 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('tab_nomer', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('stazh', models.CharField(blank=True, default='Не вказано', max_length=30, verbose_name='Cтаж')),
                ('specialization', models.CharField(blank=True, default='Не вказано', max_length=100, verbose_name='Спеціалізація')),
                ('Umovy_pryyomu', models.CharField(blank=True, default='Не вказано', max_length=250, verbose_name='Умови прийому')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ID користувача')),
            ],
        ),
    ]
