# Generated by Django 4.2.11 on 2024-05-17 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_familydoctor_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familydoctor',
            options={'verbose_name': 'Сімейного лікаря', 'verbose_name_plural': 'Сімейні лікарі'},
        ),
    ]
