# Generated by Django 4.2.11 on 2024-04-23 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Місто')),
                ('village', models.CharField(blank=True, max_length=50, null=True, verbose_name='Населений пункт')),
                ('street', models.CharField(blank=True, max_length=50, null=True, verbose_name='Вулиця')),
                ('bloc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Блок')),
                ('apartment', models.IntegerField(blank=True, null=True, verbose_name='Квартира')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('Ч', 'Чоловік'), ('Ж', 'Жінка')], default='Ч', max_length=1, verbose_name='Cтать')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата народження')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_app.address')),
            ],
        ),
    ]
