# Generated by Django 4.2.11 on 2024-05-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='apartment',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='address',
            name='house',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Будинок'),
        ),
    ]
