# Generated by Django 4.2.11 on 2024-05-06 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_address_apartment_alter_address_house'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Лікаря', 'verbose_name_plural': 'Лікарі'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Пацієнта', 'verbose_name_plural': 'Пацієнти'},
        ),
        migrations.AlterField(
            model_name='address',
            name='apartment',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Квартира'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='house',
            field=models.PositiveIntegerField(blank=True, verbose_name='Будинок'),
        ),
        migrations.AlterField(
            model_name='familydoctor',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.doctor', verbose_name='Лікар'),
        ),
        migrations.AlterField(
            model_name='familydoctor',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.patient', verbose_name='Пацієнт'),
        ),
    ]
