# Generated by Django 4.2.11 on 2024-05-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_remove_familydoctor_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='apartment',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='address',
            name='house',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Будинок'),
        ),
    ]
