# Generated by Django 4.2.11 on 2024-05-19 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_alter_address_apartment_alter_address_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
