# Generated by Django 4.2.11 on 2024-05-24 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardVaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vaccine', models.DateField(verbose_name='Дата вакцинації')),
                ('reaction', models.CharField(choices=[('Місцева', 'Місцева'), ('Загальна', 'Загальна')], max_length=20, verbose_name='Реакція на щеплення')),
                ('contraindication', models.CharField(max_length=300, verbose_name='Протипоказання')),
            ],
            options={
                'verbose_name': 'Щеплень в медичній карті',
                'verbose_name_plural': 'Щеплення в картці',
                'db_table': 'CardVaccine',
            },
        ),
        migrations.CreateModel(
            name='IndividualMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='Значення')),
            ],
            options={
                'verbose_name': 'Індивідуальну позначку',
                'verbose_name_plural': 'Індивідуальні позначки',
                'db_table': 'IndividualMarks',
            },
        ),
        migrations.CreateModel(
            name='MedCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispensary_group', models.BooleanField(default=False, verbose_name='Диспансерна група')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='Поставлено на облік')),
                ('deregistration_date', models.DateField(blank=True, null=True, verbose_name='Знято з обліку')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_app.doctor', verbose_name='ID лікаря')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth_app.patient', verbose_name='ID пацієнта')),
            ],
            options={
                'verbose_name': 'Медичну карту',
                'verbose_name_plural': 'Медичні картки',
                'db_table': 'MedCards',
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Найменування щеплення')),
                ('dose_number', models.PositiveSmallIntegerField(verbose_name='Кількість доз')),
                ('age', models.CharField(max_length=100, verbose_name='Вік для щеплення')),
                ('active_substance', models.CharField(blank=True, max_length=100, null=True, verbose_name='Активна речовина')),
                ('input_method', models.CharField(blank=True, choices=[("Внутрішньом'язова", "Внутрішньом'язова ін'єкція"), ('Підшкірна', "Підшкірна ін'єкція"), ('Внутрішньошкірна', "Внутрішньошкірна ін'єкція"), ('Перорально', 'Перорально(через рот)')], max_length=30, null=True, verbose_name='Cпосіб введення')),
                ('id_medcard', models.ManyToManyField(through='cards_app.CardVaccine', to='cards_app.medcards')),
            ],
            options={
                'verbose_name': 'Щеплень',
                'verbose_name_plural': 'Щеплення',
                'db_table': 'Vaccination',
            },
        ),
        migrations.CreateModel(
            name='SignalMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Сигнальна позначка')),
                ('id_medcard', models.ManyToManyField(through='cards_app.IndividualMarks', to='cards_app.medcards')),
            ],
            options={
                'verbose_name': 'Сигнальну позначку',
                'verbose_name_plural': 'Сигнальні позначки',
                'db_table': 'SignalMarks',
            },
        ),
        migrations.AddField(
            model_name='individualmarks',
            name='medcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards_app.medcards', verbose_name='Номер медичної карти'),
        ),
        migrations.AddField(
            model_name='individualmarks',
            name='signal_mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards_app.signalmarks', verbose_name='Cигнальна позначка'),
        ),
        migrations.CreateModel(
            name='DoctorExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_for_contacting', models.CharField(max_length=100, verbose_name='Причина звернення')),
                ('cabinet', models.CharField(blank=True, max_length=10, null=True, verbose_name='Кабінет')),
                ('date_visit', models.DateField(verbose_name='Дата прийому')),
                ('report', models.CharField(max_length=1000, verbose_name='Висновки')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auth_app.doctor', verbose_name='Особистий номер лікаря')),
                ('medcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards_app.medcards', verbose_name='Номер медичної карти')),
            ],
            options={
                'verbose_name': 'Запис про огляд',
                'verbose_name_plural': 'Записи про огляд',
                'db_table': 'DoctorExamination',
            },
        ),
        migrations.AddField(
            model_name='cardvaccine',
            name='medcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards_app.medcards', verbose_name='Номер медичної карти'),
        ),
        migrations.AddField(
            model_name='cardvaccine',
            name='vaccination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards_app.vaccination', verbose_name='Найменування щеплення'),
        ),
    ]
