# Generated by Django 4.2.11 on 2024-05-17 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_remove_familydoctor_group'),
        ('cards_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medcards',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_app.doctor', verbose_name='ID лікаря'),
        ),
        migrations.AlterField(
            model_name='medcards',
            name='registration_date',
            field=models.DateField(auto_now_add=True, verbose_name='Поставлено на облік'),
        ),
    ]
