# Generated by Django 4.2.11 on 2024-05-06 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='individualmarks',
            options={'verbose_name': 'Індивідуальні позначки', 'verbose_name_plural': 'Індивідуальну позначку'},
        ),
        migrations.AlterModelOptions(
            name='medcards',
            options={'verbose_name': 'Медичних карт', 'verbose_name_plural': 'Медичну карту'},
        ),
        migrations.AlterModelOptions(
            name='signalmarks',
            options={'verbose_name': 'Сигнальні позначки', 'verbose_name_plural': 'Сигнальну позначку'},
        ),
    ]
