# Generated by Django 4.2.11 on 2024-05-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards_app', '0002_alter_medcards_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medcards',
            name='dispensary_group',
            field=models.BooleanField(default=False, verbose_name='Диспансерна група'),
        ),
    ]
