# Generated by Django 4.2.11 on 2024-05-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards_app', '0002_alter_medcards_deregistration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardvaccine',
            name='consignment',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Серія вакцини'),
        ),
    ]
