# Generated by Django 4.2.11 on 2024-05-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards_app', '0003_cardvaccine_consignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardvaccine',
            name='consignment',
            field=models.CharField(max_length=20, verbose_name='Серія вакцини'),
        ),
    ]
