# Generated by Django 4.2.11 on 2024-05-27 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards_app', '0004_alter_cardvaccine_consignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardvaccine',
            name='vaccination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cards_app.vaccination', verbose_name='Найменування щеплення'),
        ),
    ]
