# Generated by Django 4.2.11 on 2024-05-30 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards_app', '0005_alter_cardvaccine_vaccination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardvaccine',
            old_name='consignment',
            new_name='product_series',
        ),
    ]
